### ISSUE TITLE
自定义消息接收不到

### ISSUE THREAD

**Issue by ToryCrox** [rongcloud/im-flutter-wrapper#6]
1. Flutter端收不到服务端发的自定义消息，看了下源码，发现自定义消息rawData不能为空，但是收到的自定义消息根本没这个字段
![image](https://github.com/rongcloud/im-flutter-wrapper/assets/16319702/546657c1-c62e-431a-b0e2-304e6872d8f2)

2. 又看了下example，发现java端还得写对应的类，为啥要搞这么麻烦？java端我也加了，但是还是收不到，因为还是没有raowData，有没有个设置的地方，陷入死胡同了。

服务端使用这个方式发送的消息: https://doc.rongcloud.cn/imserver/server/v1/system/send-private

有大佬解答一下吗？

**Comment by Pgrammerybj** [comment]
同问，公司的flutter项目也遇到过类似的问题，@官方出来解惑一下呗

**Comment by smiletomyself** [comment]
I have encountered the same issue and hope for a prompt fix. Thank you.  @RongCloudAdmin

**Comment by LiJiyaoisrunning** [comment]
> 1. Flutter端收不到服务端发的自定义消息，看了下源码，发现自定义消息rawData不能为空，但是收到的自定义消息根本没这个字段
>    ![image](https://user-images.githubusercontent.com/16319702/275332375-546657c1-c62e-431a-b0e2-304e6872d8f2.png)
> 2. 又看了下example，发现java端还得写对应的类，为啥要搞这么麻烦？java端我也加了，但是还是收不到，因为还是没有raowData，有没有个设置的地方，陷入死胡同了。
> 
> 服务端使用这个方式发送的消息: https://doc.rongcloud.cn/imserver/server/v1/system/send-private
> 
> 有大佬解答一下吗？

rawData要求是不能等于空字符串，等于null的时候那个判断是能通过的

**Comment by ToryCrox** [comment]
https://help.rongcloud.cn/t/topic/953  官方文档里面，用这个方式
